modLoader = "javafml"
loaderVersion = "[4,)"
license = "AGPL-3.0-only"

[[mods]]
modId = "chnh_core"
version = "1.0.0"
displayName = "CHNH Core"
authors = "MinBaka"
description = "CHNH Core Custom Effects"
logoFile = "logo.png"

[[dependencies.chnh_core]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chnh_core]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"